<a href="https://colab.research.google.com/github/nguyennhatdangkhoa20130295/ML_Thu3_Ca4/blob/main/Lab_5_20130295_NguyenNhatDangKhoa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with **SVM** to classification tasks and compare its performance with other competitive algorithms. In general, **SVM** is one of the most popular and widely used supervised machine learning algorithms.

*   **Deadline: 23:59, 17/03/2023**



# Import libraries

In [1]:
# code
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'

Mounted at /content/gdrive
/content/gdrive/MyDrive/ML


In [52]:
#code
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score 
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from prettytable import PrettyTable
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

#Task 1. 
For breast cancer dataset (https://tinyurl.com/3vme8hr3) which could be loaded from datasets in sklearn as follows:

```
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()
```

*   1.1.	Apply SVM algorithm to above dataset using linear kernel.
*   1.2.	Compare the obtained results with other competitive algorithms (Logistic Regression, Decision Tree, kNN) based on metrics: accuracy, precision, recall, f1 measures.



In [64]:
# code
# 1.1
cancer = datasets.load_breast_cancer()
X = cancer.data
y = cancer.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)
svm_model = SVC(kernel ='linear')
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[45  3]
 [ 2 64]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        48
           1       0.96      0.97      0.96        66

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [66]:
# 1.2

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

svm_acc = accuracy_score(y_test, y_pred)
svm_prec = precision_score(y_test, y_pred)
svm_recall = recall_score(y_test, y_pred)
svm_f1 = f1_score(y_test, y_pred)

lr_acc = accuracy_score(y_test, lr_pred)
lr_prec = precision_score(y_test, lr_pred)
lr_recall = recall_score(y_test, lr_pred)
lr_f1 = f1_score(y_test, lr_pred)

dt_acc = accuracy_score(y_test, dt_pred)
dt_prec = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)

knn_acc = accuracy_score(y_test, knn_pred)
knn_prec = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)

t = PrettyTable(['Algorithm','Accuracy', 'Precision', 'Recall', 'F1'])
t.add_row(["Logistic Regression", lr_acc, lr_prec, lr_recall, lr_f1])
t.add_row(["Decision Tree", dt_acc, dt_prec, dt_recall, dt_f1])
t.add_row(["kNN", knn_acc, knn_prec, knn_recall, knn_f1])

print(t)


+---------------------+--------------------+--------------------+--------------------+--------------------+
|      Algorithm      |      Accuracy      |     Precision      |       Recall       |         F1         |
+---------------------+--------------------+--------------------+--------------------+--------------------+
| Logistic Regression | 0.9298245614035088 | 0.9264705882352942 | 0.9545454545454546 | 0.9402985074626866 |
|    Decision Tree    | 0.9473684210526315 | 0.9411764705882353 | 0.9696969696969697 | 0.955223880597015  |
|         kNN         | 0.9385964912280702 | 0.927536231884058  | 0.9696969696969697 | 0.9481481481481481 |
+---------------------+--------------------+--------------------+--------------------+--------------------+


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#Task 2. 

*   1.1.	Perform SVM algorithm to **Iris dataset** using **linear kernel**.
*   1.2.	Compare the obtained results in 1.1 with SVM using other kernels (**Polynomial Kernel, Gaussian Kernel, Sigmoid Kernel, Radial Basis Function Kernel**). Some metrics could be used: accuracy, precision, recall, f1 measures





In [71]:
# code
# 2.1
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)
svm_model = SVC(kernel ='linear')
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.92      1.00      0.96        11
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [72]:
# 2.2

svm_poly = SVC(kernel='poly')
svm_poly.fit(X_train, y_train)
svm_poly_pred = svm_poly.predict(X_test)

svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)
svm_rbf_pred = svm_rbf.predict(X_test)

svm_sigmoid = SVC(kernel='sigmoid')
svm_sigmoid.fit(X_train, y_train)
svm_sigmoid_pred = svm_sigmoid.predict(X_test)

poly_acc = accuracy_score(y_test, svm_poly_pred)
poly_prec = precision_score(y_test, svm_poly_pred, average='macro')
poly_recall = recall_score(y_test, svm_poly_pred, average='macro')
poly_f1 = f1_score(y_test, svm_poly_pred, average='macro')

rbf_acc = accuracy_score(y_test, svm_rbf_pred)
rbf_prec = precision_score(y_test, svm_rbf_pred, average='macro')
rbf_recall = recall_score(y_test, svm_rbf_pred, average='macro')
rbf_f1 = f1_score(y_test, svm_rbf_pred, average='macro')

sigmoid_acc = accuracy_score(y_test, svm_sigmoid_pred)
sigmoid_prec = precision_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_recall = recall_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_f1 = f1_score(y_test, svm_sigmoid_pred, average='macro')


t = PrettyTable(['Kernel','Accuracy', 'Precision', 'Recall', 'F1'])
t.add_row(["Polynomial", poly_acc, poly_prec, poly_recall, poly_f1])
t.add_row(["Radial Basis Function", rbf_acc, rbf_prec, rbf_recall, rbf_f1])
t.add_row(["Sigmoid", sigmoid_acc, sigmoid_prec, sigmoid_recall, sigmoid_f1])

print(t)

+-----------------------+---------------------+---------------------+--------------------+---------------------+
|         Kernel        |       Accuracy      |      Precision      |       Recall       |          F1         |
+-----------------------+---------------------+---------------------+--------------------+---------------------+
|       Polynomial      |  0.9666666666666667 |  0.9722222222222222 | 0.9696969696969697 |  0.9696342305037957 |
| Radial Basis Function |         1.0         |         1.0         |        1.0         |         1.0         |
|        Sigmoid        | 0.26666666666666666 | 0.08888888888888889 | 0.3333333333333333 | 0.14035087719298248 |
+-----------------------+---------------------+---------------------+--------------------+---------------------+


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Task 3. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with mnist dataset based on accuracy, precision, recall, f1 measures.


In [74]:
# code
data = datasets.load_digits()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)
svm_model = SVC(kernel ='linear')
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

svm_acc = accuracy_score(y_test, y_pred)
svm_prec = precision_score(y_test, y_pred, average='macro')
svm_recall = recall_score(y_test, y_pred, average='macro')
svm_f1 = f1_score(y_test, y_pred, average='macro')

lr_acc = accuracy_score(y_test, lr_pred)
lr_prec = precision_score(y_test, lr_pred, average='macro')
lr_recall = recall_score(y_test, lr_pred, average='macro')
lr_f1 = f1_score(y_test, lr_pred, average='macro')

dt_acc = accuracy_score(y_test, dt_pred)
dt_prec = precision_score(y_test, dt_pred, average='macro')
dt_recall = recall_score(y_test, dt_pred, average='macro')
dt_f1 = f1_score(y_test, dt_pred, average='macro')

knn_acc = accuracy_score(y_test, knn_pred)
knn_prec = precision_score(y_test, knn_pred, average='macro')
knn_recall = recall_score(y_test, knn_pred, average='macro')
knn_f1 = f1_score(y_test, knn_pred, average='macro')

svm_poly = SVC(kernel='poly')
svm_poly.fit(X_train, y_train)
svm_poly_pred = svm_poly.predict(X_test)

svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)
svm_rbf_pred = svm_rbf.predict(X_test)

svm_sigmoid = SVC(kernel='sigmoid')
svm_sigmoid.fit(X_train, y_train)
svm_sigmoid_pred = svm_sigmoid.predict(X_test)

poly_acc = accuracy_score(y_test, svm_poly_pred)
poly_prec = precision_score(y_test, svm_poly_pred, average='macro')
poly_recall = recall_score(y_test, svm_poly_pred, average='macro')
poly_f1 = f1_score(y_test, svm_poly_pred, average='macro')

rbf_acc = accuracy_score(y_test, svm_rbf_pred)
rbf_prec = precision_score(y_test, svm_rbf_pred, average='macro')
rbf_recall = recall_score(y_test, svm_rbf_pred, average='macro')
rbf_f1 = f1_score(y_test, svm_rbf_pred, average='macro')

sigmoid_acc = accuracy_score(y_test, svm_sigmoid_pred)
sigmoid_prec = precision_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_recall = recall_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_f1 = f1_score(y_test, svm_sigmoid_pred, average='macro')

t = PrettyTable(['Kernels/Algorithms','Accuracy', 'Precision', 'Recall', 'F1'])
t.add_row(["Logistic Regression", lr_acc, lr_prec, lr_recall, lr_f1])
t.add_row(["Decision Tree", dt_acc, dt_prec, dt_recall, dt_f1])
t.add_row(["kNN", knn_acc, knn_prec, knn_recall, knn_f1])
t.add_row(["Polynomial", poly_acc, poly_prec, poly_recall, poly_f1])
t.add_row(["Radial Basis Function", rbf_acc, rbf_prec, rbf_recall, rbf_f1])
t.add_row(["Sigmoid", sigmoid_acc, sigmoid_prec, sigmoid_recall, sigmoid_f1])

print(t)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


+-----------------------+--------------------+--------------------+--------------------+--------------------+
|   Kernels/Algorithms  |      Accuracy      |     Precision      |       Recall       |         F1         |
+-----------------------+--------------------+--------------------+--------------------+--------------------+
|  Logistic Regression  | 0.9805555555555555 | 0.9797161127403061 | 0.9803326439056178 | 0.979849347985897  |
|     Decision Tree     | 0.8722222222222222 | 0.8703573192019979 | 0.8704393225064113 | 0.8694127609290924 |
|          kNN          | 0.9861111111111112 | 0.9847186147186147 | 0.984737554112554  | 0.9845359412093282 |
|       Polynomial      | 0.9888888888888889 | 0.9878411127403062 | 0.9884974747474746 | 0.9880884444106472 |
| Radial Basis Function | 0.9833333333333333 | 0.9820391414141414 | 0.983201307500088  | 0.9825488798628668 |
|        Sigmoid        | 0.9277777777777778 | 0.9259609249682779 | 0.9256486959686369 | 0.9250830689097755 |
+---------

#Task 4. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with **credit card dataset** based on accuracy, precision, recall, f1 measures.

*   Give some comments on the obtained results
*   Identify issues with dataset, and propose the solutions to these issues



In [ ]:
# code
data = pd.read_csv("creditcard.csv")
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)
svm_model = SVC(kernel ='linear')
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

svm_acc = accuracy_score(y_test, y_pred)
svm_prec = precision_score(y_test, y_pred, average='macro')
svm_recall = recall_score(y_test, y_pred, average='macro')
svm_f1 = f1_score(y_test, y_pred, average='macro')

lr_acc = accuracy_score(y_test, lr_pred)
lr_prec = precision_score(y_test, lr_pred, average='macro')
lr_recall = recall_score(y_test, lr_pred, average='macro')
lr_f1 = f1_score(y_test, lr_pred, average='macro')

dt_acc = accuracy_score(y_test, dt_pred)
dt_prec = precision_score(y_test, dt_pred, average='macro')
dt_recall = recall_score(y_test, dt_pred, average='macro')
dt_f1 = f1_score(y_test, dt_pred, average='macro')

knn_acc = accuracy_score(y_test, knn_pred)
knn_prec = precision_score(y_test, knn_pred, average='macro')
knn_recall = recall_score(y_test, knn_pred, average='macro')
knn_f1 = f1_score(y_test, knn_pred, average='macro')

svm_poly = SVC(kernel='poly')
svm_poly.fit(X_train, y_train)
svm_poly_pred = svm_poly.predict(X_test)

svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)
svm_rbf_pred = svm_rbf.predict(X_test)

svm_sigmoid = SVC(kernel='sigmoid')
svm_sigmoid.fit(X_train, y_train)
svm_sigmoid_pred = svm_sigmoid.predict(X_test)

poly_acc = accuracy_score(y_test, svm_poly_pred)
poly_prec = precision_score(y_test, svm_poly_pred, average='macro')
poly_recall = recall_score(y_test, svm_poly_pred, average='macro')
poly_f1 = f1_score(y_test, svm_poly_pred, average='macro')

rbf_acc = accuracy_score(y_test, svm_rbf_pred)
rbf_prec = precision_score(y_test, svm_rbf_pred, average='macro')
rbf_recall = recall_score(y_test, svm_rbf_pred, average='macro')
rbf_f1 = f1_score(y_test, svm_rbf_pred, average='macro')

sigmoid_acc = accuracy_score(y_test, svm_sigmoid_pred)
sigmoid_prec = precision_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_recall = recall_score(y_test, svm_sigmoid_pred, average='macro')
sigmoid_f1 = f1_score(y_test, svm_sigmoid_pred, average='macro')

t = PrettyTable(['Kernels/Algorithms','Accuracy', 'Precision', 'Recall', 'F1'])
t.add_row(["Logistic Regression", lr_acc, lr_prec, lr_recall, lr_f1])
t.add_row(["Decision Tree", dt_acc, dt_prec, dt_recall, dt_f1])
t.add_row(["kNN", knn_acc, knn_prec, knn_recall, knn_f1])
t.add_row(["Polynomial", poly_acc, poly_prec, poly_recall, poly_f1])
t.add_row(["Radial Basis Function", rbf_acc, rbf_prec, rbf_recall, rbf_f1])
t.add_row(["Sigmoid", sigmoid_acc, sigmoid_prec, sigmoid_recall, sigmoid_f1])

print(t)

#Finally,
Save a copy in your Github. Remember renaming the notebook.